### ISSUE TITLE
Todo ...

### ISSUE THREAD

**Issue by YouDirk** [YouDirk/libathome#4]
* [x] Rename `src/primeathome` -> `src/project`
* [x] Remove `PROJECT_NAME` from `makefile.config.mk`
* [x] For `doc`: `.gitignore`, `clean` targets
* [x] Start browser on target `doc`
* [x] Add version to `makefile.config.mk`
* [x] Complete generating 'Doxyfile-project'
* [x] add target doc to `makefile.config-global.mk`

**Comment by YouDirk** [comment]
closed via 775aa97683398179867c8da140890d5797262852
