### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by YouDirk** [YouDirk/libathome#5]
* [x] Implement backtrace for Windows/mingw
* [x] Add tag, such like mingw-dev
* [x] Log output after Logger initialization
* [x] document `throw` stuff
