### ISSUE TITLE
Some things TODO

### ISSUE THREAD

**Issue by YouDirk** [YouDirk/libathome#9]
* [x] Test Doxygen `generate_treeview`
* [x] Test Doxygen if `@home` warnings are filtered
* [x] Doxygen set `generate_man`
* [x] Rename `src/libathome-common/libathome-*{,.templ}.hpp`
* [ ] Make implicite version check, if Header-Files using the same version as shared linked library
* [ ] Begin `Filesystem::` and Log-Rotation  stuff
* [x] Update GitHub Sponsors page (remove Patreon link?)
* [x] Make Credits section in `README.md` (make Todo Issue `--credits`)
* [x] Create `CONTRIBUTING.md`, includes Sponsoring as kind of contirbution
* [x] Link Sponsors page in `README.md`, `CONTRIBUTING.md`
* [x] Add https://youdirk.github.io/libathome-doc/ to Google search index
* [x] `@ref` All Doxygen refernces to enforce warnings if something brokes
